Iptables config was failing to install:
Error: Could not set 'present' on ensure: No such file or directory @
dir_s_rmdir - /etc/iptables/rules.v420160614-12703-1xjxje3.lock at
55:/etc/puppet/modules/rpki/manifests/iptables.pp

This file can't get written because the /etc/iptables directory is
non-existent on debian-8 (and previous debian as well I believe).